# Generated by Django 2.1.15 on 2025-04-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='acceslog',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.Employe'),
        ),
    ]
