# Generated by Django 2.1.15 on 2025-04-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceslog',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='serveur.Employe'),
        ),
        migrations.AlterField(
            model_name='visage',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visages', to='serveur.Employe'),
        ),
    ]
