# Generated by Django 2.1.15 on 2025-04-27 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0002_auto_20250427_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceslog',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.Employe'),
        ),
        migrations.AlterField(
            model_name='visage',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.Employe'),
        ),
    ]
