# Generated by Django 2.1.15 on 2025-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0004_historiqueacces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueacces',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visage',
            name='image_path',
            field=models.ImageField(upload_to='visages/'),
        ),
    ]
