# Generated by Django 2.1.15 on 2025-05-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0005_auto_20250503_1536'),
    ]

    operations = [
    ]
