# Generated by Django 2.1.15 on 2025-05-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0006_auto_20250503_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueacces',
            name='employe',
        ),
        migrations.DeleteModel(
            name='HistoriqueAcces',
        ),
    ]
